### ISSUE TITLE
Dataset location

### ISSUE THREAD

**Issue by duerrsimon** [jasonkyuyim/multiflow#1]
Just checked the repo and saw that the datasets are being hosted on Dropbox. 
I think you should put the dataset e.g on Zenodo (50GB free). 

Dropbox has quite low bandwidth limits (20GB per day) and is not very future proof if somebody wants to download the dataset in a few years. 

Great work and looking forward to play with this more :)

**Comment by jasonkyuyim** [comment]
THanks for the suggestion! I switched to zenodo.
