### ISSUE TITLE
order of return values from dataset_creation 

### ISSUE THREAD

**Issue by phbradley** [jasonkyuyim/multiflow#10]
Hi there,
Thanks for sharing this beautiful code base! The code really is a pleasure to read. I can't believe how easy it has been to install and run training and inference! Anyhow, I was poking around trying to understand how things work and I have a random question. No hurry at all of course.

dataset_creation is called here:

https://github.com/jasonkyuyim/multiflow/blob/main/multiflow/experiments/inference_se3_flows.py#L166

but based on the function definition it almost seems like the order of return values is swapped 

https://github.com/jasonkyuyim/multiflow/blob/main/multiflow/experiments/utils.py#L69

Like I said, I've just started poking around so my apologies if this is totally off base. 
Thanks,
Phil

**Comment by jasonkyuyim** [comment]
Ah yes this is confusing... We wanted to use the larger split for evaluation and were lazy. We don't use `pdb_post2021_dataset` for training so there isn't any time-based data leakage. I think this is ok. Only a handful examples should be left out.

**Comment by phbradley** [comment]
OK, super, thanks for clarifying, and sorry to pester!
