### ISSUE TITLE
Question about loss weight

### ISSUE THREAD

**Issue by Wangchentong** [jasonkyuyim/multiflow#3]
Hi Jason,

Nice work! 

I notice that the auxiliary loss weight in base.yaml is set to 0, which is different from the FrameDiff and Frameflow, do you observe a better performance by removing the auxiliary loss?

**Comment by jasonkyuyim** [comment]
Hi, we noticed the auxiliary losses are not necessary anymore. It simplified training so we dropped it. There wasn't a loss in performance from my experiments.
